# AppVeyor.com is a Continuous Integration service to build and run tests under
# Windows
image: Visual Studio 2019

environment:
  # see https://www.appveyor.com/docs/build-environment/#python
  matrix:
    - TARGET_ARCH: "x64"
      CONDA_PY: "310"
    - TARGET_ARCH: "x64"
      CONDA_PY: "311"
    - TARGET_ARCH: "x64"
      CONDA_PY: "312"
    - TARGET_ARCH: "x64"
      CONDA_PY: "313"


# We always use a 64-bit machine.
platform:
- x64

install:
  - ps: $env:CONDA_INSTALL_LOCN="$env:USERPROFILE\Miniconda3"
  - ps: Invoke-WebRequest -Uri https://repo.anaconda.com/miniconda/Miniconda3-py312_24.9.2-0-Windows-x86_64.exe -OutFile Miniconda3.exe
  - ps: ( Get-FileHash -Algorithm SHA256 Miniconda3.exe ).Hash -eq '3a8897cc5d27236ade8659f0e119f3a3ccaad68a45de45bfdd3102d8bec412ab'
  - ps: Start-Process Miniconda3.exe -Wait -ArgumentList @('/S', '/InstallationType=JustMe', '/RegisterPython=1', '/D="$env:CONDA_INSTALL_LOCN"')
  - ps: $env:Path += ";$env:CONDA_INSTALL_LOCN\Scripts;$env:CONDA_INSTALL_LOCN\Library\bin"
  - ps: conda init powershell
  - ps: conda config --set always_yes yes
  - ps: conda config --set changeps1 no
  - ps: conda config --set auto_update_conda false
  - ps: conda config --set notify_outdated_conda false
#  - ps: conda update --yes --quiet conda
  - ps: conda info -a

  # Install the build and runtime dependencies of the project.
  - ps: $envScript=".\ci\appveyor\py$($env:CONDA_PY).ps1"
  - ps: "& $envScript"
  - ps: python "ci\render-requirements.py" "ci\deps\requirements.yaml.tmpl" > environment.yaml
  # work-around for https://github.com/conda/conda/issues/14355
  - ps: "& { $env:PYTHONWARNINGS = \"ignore::FutureWarning\"; conda env create -n sksurv-test --file environment.yaml }"
  - cmd: call %CONDA_INSTALL_LOCN%\Scripts\activate.bat sksurv-test
  - cmd: conda list
  # Initialize the submodules
  - cmd: git submodule update --init --recursive
  # Create binary packages for the project.
  - cmd: python -m build .
  - ps: "ls dist"

  # Install the generated wheel package to test it
  - cmd: pip install --exists-action=w --pre --no-index --find-links dist/ scikit-survival
  - cmd: rmdir sksurv /s /q

test_script:
  - cmd: set "PYTHONWARNINGS=default"
  - cmd: pytest -m "not slow"

artifacts:
  # Archive the generated wheel package in the ci.appveyor.com build report.
  - path: dist\*

# Skip .NET project specific build phase.
build: off
