[build-system]
requires = [
    "setuptools>=45",
    "wheel",
    "setuptools_scm[toml]>=6.4",
    "Cython>=0.29.16",
    "numpy==1.14.6; python_version=='3.7' and platform_system!='AIX'",
    "numpy==1.17.3; python_version=='3.8' and platform_system!='AIX'",
    "numpy==1.19.3; python_version=='3.9'",
    "numpy==1.21.4; python_version=='3.10'",
    "numpy; python_version>'3.10'",
    "scikit-learn==1.0.0; python_version<='3.9'",
    "scikit-learn==1.0.2; python_version=='3.10'",
    "scikit-learn; python_version>'3.10'",
]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
