name: macOS
on:
  push:
  pull_request:
  schedule:
    - cron: '0 6 1 * *'

jobs:
  checks:
    runs-on: macos-latest
    name: Build and check
    strategy:
      matrix:
        config:
          - py37_pandas025_numpy117_sklearn10
          - py38_pandas10_numpy118_sklearn10
          - py38_pandas11_numpy119_sklearn10
          - py39_pandas13_numpy121_sklearn10
          - py310_pandas14_numpy121_sklearn10
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: true
      - name: Adding conda to PATH
        run: echo "${CONDA}/bin" >> $GITHUB_PATH
      - name: Set dependencies
        id: dependencies
        run: |
          source ci/deps/${{ matrix.config }}.sh
          echo "CONDA_PYTHON_VERSION=${CONDA_PYTHON_VERSION}" >> $GITHUB_ENV
          echo "PANDAS_VERSION=${PANDAS_VERSION}" >> $GITHUB_ENV
          echo "NUMPY_VERSION=${NUMPY_VERSION}" >> $GITHUB_ENV
          echo "SKLEARN_VERSION=${SKLEARN_VERSION}" >> $GITHUB_ENV
          echo "NO_SLOW=${NO_SLOW}" >> $GITHUB_ENV
          echo "::set-output name=py_version::${CONDA_PYTHON_VERSION}"
          echo "::set-output name=requirements::ci/deps/${{ matrix.config }}.sh"
          echo "::set-output name=conda_pkgs::$(${CONDA}/bin/python -c "from conda.base.context import context; print(context.pkgs_dirs[0])")"
      - name: Cache downloaded packages
        uses: actions/cache@v2
        with:
          path: ${{ steps.dependencies.outputs.conda_pkgs }}
          key: ${{ runner.os }}-conda-${{ steps.dependencies.outputs.py_version }}-${{ hashFiles(steps.dependencies.outputs.requirements, 'requirements/*.txt') }}
          restore-keys: |
            ${{ runner.os }}-conda-${{ steps.dependencies.outputs.py_version }}-
      - name: Create Conda Environment
        run: |
          sudo chown -R $USER $CONDA
          conda config --set always_yes yes --set changeps1 no
          conda update -q conda
          ci/setup_env.sh ${{ runner.os }}
      - name: Install Dependencies
        run: |
          python3 ci/list-requirements.py requirements/dev.txt > /tmp/conda-req.txt
          conda install -c sebp -n sksurv-test --file /tmp/conda-req.txt
          conda list -n sksurv-test
      - name: Build package
        run: |
          sudo xcode-select -s "/Applications/Xcode_13.2.1.app"
          source activate sksurv-test
          pip wheel --wheel-dir dist/ --no-binary scikit-survival --no-deps -e .
          pip install --exists-action=w --pre --no-index --find-links dist/ scikit-survival
          rm -fr build dist
      - name: Run Tests
        run: |
          source activate sksurv-test
          ci/run_tests.sh
